"""
Test simplified flow: Plate -> NIK generation without address/dialog
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from utils.indonesian_plates import IndonesianPlateManager, VehicleOwner

def test_nik_from_plate():
    """Test generating NIK from plate region code"""
    test_cases = [
        ('B', 'Jakarta (B)'),
        ('D', 'Bandung (D)'),
        ('F', 'Bogor (F)'),
        ('A', 'Banten (A)'),
        ('T', 'Surabaya (T)'),
    ]
    
    print("=" * 60)
    print("TEST: NIK Generation from Plate Region Code")
    print("=" * 60)
    
    for region_code, description in test_cases:
        nik = IndonesianPlateManager.generate_nik_from_plate(region_code)
        print(f"\nPlate Region: {description}")
        print(f"Generated NIK: {nik}")
        print(f"  - Length: {len(nik)} (should be 16)")
        print(f"  - Province Code: {nik[:2]}")
        print(f"  - City Code: {nik[2:4]}")
        print(f"  - District Code: {nik[4:6]}")
        print(f"  - Birth Day: {nik[6:8]}")
        print(f"  - Birth Month: {nik[8:10]}")
        print(f"  - Birth Year: {nik[10:12]}")
        print(f"  - Sequential: {nik[12:16]}")
        
        # Validate format
        assert len(nik) == 16, f"NIK should be 16 digits, got {len(nik)}"
        assert nik.isdigit(), f"NIK should contain only digits, got {nik}"
    
    print("\n" + "=" * 60)
    print("✅ All tests passed!")
    print("=" * 60)


def test_owner_generation():
    """Test generating owner from region"""
    print("\n\nTEST: Owner Generation (Simple)")
    print("=" * 60)
    
    test_cases = [
        ('DKI Jakarta', 'Jakarta Selatan', '31', 'roda_empat'),
        ('Jawa Barat', 'Bandung', '32', 'roda_dua'),
        ('Banten', 'Tangerang', '36', 'roda_empat'),
    ]
    
    for region, sub_region, province_code, vehicle_type in test_cases:
        owner = VehicleOwner.generate_random_owner(
            region=region,
            sub_region=sub_region,
            vehicle_type=vehicle_type,
            required_province_code=province_code
        )
        
        print(f"\nRegion: {region} / {sub_region}")
        print(f"  Owner ID (NIK): {owner.owner_id}")
        print(f"  Name: {owner.name}")
        print(f"  Vehicle Type: {owner.vehicle_type}")
        print(f"  STNK Status: {'Active' if owner.stnk_status else 'Expired'}")
        print(f"  SIM Status: {'Active' if owner.sim_status else 'Expired'}")
        print(f"  Address: {getattr(owner, 'address', 'NOT STORED')}")
        
        # Validate no address field
        assert not hasattr(owner, 'address') or owner.__dict__.get('address') is None, \
            "Owner should not have address field after simplification"
    
    print("\n" + "=" * 60)
    print("✅ Owner generation test passed!")
    print("=" * 60)


def test_plate_to_owner():
    """Test complete flow: Generate plate -> Parse -> Generate owner"""
    print("\n\nTEST: Complete Flow - Plate to Owner")
    print("=" * 60)
    
    # Generate a plate
    plate = IndonesianPlateManager.generate_plate()
    print(f"\nGenerated Plate: {plate}")
    
    # Parse the plate
    parsed = IndonesianPlateManager.parse_plate(plate)
    if parsed:
        print(f"Parsed Region: {parsed['region_name']}")
        print(f"Parsed Sub-region: {parsed.get('sub_region', 'N/A')}")
        print(f"Plate Format: {parsed.get('format', 'N/A')}")
        
        # Generate NIK from plate region code
        nik = IndonesianPlateManager.generate_nik_from_plate(parsed['region_code'])
        print(f"Generated NIK: {nik}")
        
        # Generate owner
        owner = VehicleOwner.generate_random_owner(
            region=parsed['region_name'],
            sub_region=parsed.get('sub_region', parsed['region_name']),
            required_province_code=IndonesianPlateManager.get_province_code_from_plate_code(parsed['region_code'])
        )
        
        print(f"\nOwner Generated:")
        print(f"  Owner ID: {owner.owner_id}")
        print(f"  Name: {owner.name}")
        print(f"  Vehicle Type: {owner.vehicle_type}")
        
        # The NIK from generate_nik_from_plate might differ from owner.owner_id
        # since owner_id is generated by generate_random_owner
        # This is OK - both methods produce valid NIKs
        
    print("\n" + "=" * 60)
    print("✅ Complete flow test passed!")
    print("=" * 60)


if __name__ == '__main__':
    test_nik_from_plate()
    test_owner_generation()
    test_plate_to_owner()
    
    print("\n\n" + "=" * 60)
    print("🎉 ALL SIMPLIFIED FLOW TESTS PASSED!")
    print("=" * 60)
    print("\nSimplified System Summary:")
    print("✅ Plate parsing works")
    print("✅ NIK generation from plate code works")
    print("✅ Owner generation without address works")
    print("✅ No dialog generation")
    print("✅ Simple, minimal implementation")
